let bricks=[];
const searchInput=document.querySelector('#brick-search'),searchButton=document.querySelector('#search-button'),locationFilter=document.querySelector('#location-filter'),clearButton=document.querySelector('#clear-search'),results=document.querySelector('#results'),resultSummary=document.querySelector('#result-summary'),emptyState=document.querySelector('#empty-state'),dialog=document.querySelector('#brick-dialog'),dialogBody=document.querySelector('#dialog-body'),dialogClose=document.querySelector('#dialog-close');
const STORY_FORM_BASE='https://docs.google.com/forms/d/e/1FAIpQLSdOFzgx8B_7indD-BukJ8HxrZsMzTPBzb68bQur6vEs8nYoRg/viewform?usp=pp_url';
function brickStoryFormUrl(b){return STORY_FORM_BASE+'&entry.151104679='+encodeURIComponent(b.id)+'&entry.284776136='+encodeURIComponent(b.inscription);}
const escapeHtml=str=>String(str??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const normalize=s=>String(s??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function searchText(b){return normalize([b.id,b.inscription,b.location,b.site,b.area,`column ${b.column}`,`brick ${b.brick_number}`].join(' '));}
function shortTitle(b){const clean=String(b.inscription??'').replace(/\s+/g,' ').trim();if(!clean)return'';const quotePos=clean.search(/["“”]/);if(quotePos>=4){const before=clean.slice(0,quotePos).trim().replace(/[,:;\-–—]+$/,'').trim();if(before.length>=4&&before.length<=80)return before;}if(clean.length<=62)return clean;const clipped=clean.slice(0,63),last=clipped.lastIndexOf(' ');return(last>30?clipped.slice(0,last):clean.slice(0,62)).trim()+'…';}
function selectedLocation(){const value=locationFilter.value;if(!value)return{area:'',col:''};const [area,col]=value.split('|');return{area,col};}
function buildFrontGrid(selectedBrick=null){const grid=document.querySelector('#front-grid');if(!grid)return;const counts=[56,60,60,59,61,61,59,60,60],max=Math.max(...counts);let out='<div class="grid-corner">Brick</div>'+counts.map((_,i)=>'<div class="grid-colhead">'+(i+1)+'</div>').join('');for(let n=1;n<=max;n++){out+='<div class="grid-rowhead">'+n+'</div>';for(let c=1;c<=9;c++){const exists=n<=counts[c-1],selected=selectedBrick&&selectedBrick.area==='Front Walkway'&&Number(selectedBrick.column)===c&&Number(selectedBrick.brick_number)===n;out+='<div class="grid-cell '+(exists?'':'grid-gap')+(selected?' grid-selected':'')+'">'+(exists?n:'')+'</div>';}}grid.innerHTML=out;}
function render(){const q=normalize(searchInput.value),{area,col}=selectedLocation();const matches=bricks.filter(b=>{const queryOK=!q||q.split(' ').every(term=>searchText(b).includes(term));return queryOK&&(!area||b.area===area)&&(!col||String(b.column)===col);});const shown=(!q&&!area&&!col)?matches.slice(0,12):matches;resultSummary.textContent=(!q&&!area&&!col)?`Showing 12 of ${bricks.length} currently indexed Fort Johnston bricks`:`${matches.length} result${matches.length===1?'':'s'}${q?` for “${searchInput.value.trim()}”`:''}`;results.innerHTML='';emptyState.hidden=matches.length!==0;shown.forEach(b=>{const card=document.createElement('article');card.className='result-card';const photo=b.image?`<img class="result-photo" src="${escapeHtml(b.image)}" alt="Photograph of brick ${escapeHtml(b.id)}">`:`<div class="photo-missing">Brick photograph<br>coming soon</div>`;card.innerHTML=`${photo}<div class="result-copy"><h3>${escapeHtml(shortTitle(b))}</h3><p class="result-inscription">${escapeHtml(b.inscription)}</p><div class="meta"><strong>Location</strong><span>${escapeHtml(b.location)}</span><strong>Brick ID</strong><span>${escapeHtml(b.id)}</span></div><div class="result-actions"><button class="map-link" type="button">How to find it</button><a class="story-link" href="${escapeHtml(brickStoryFormUrl(b))}" target="_blank" rel="noopener">Tell Us About This Brick</a></div></div>`;card.querySelector('.result-copy').addEventListener('dblclick',()=>openBrick(b));if(b.image)card.querySelector('.result-photo').addEventListener('click',()=>openBrick(b));card.querySelector('.map-link').addEventListener('click',()=>{buildFrontGrid(b);document.querySelector('#locations').scrollIntoView({behavior:'smooth',block:'start'});});results.appendChild(card);});}
function openBrick(b){dialogBody.innerHTML=`<div class="dialog-content"><h3>${escapeHtml(b.id)}</h3>${b.image?`<img class="dialog-photo" src="${escapeHtml(b.image)}" alt="Brick photograph">`:''}<div class="dialog-inscription">${escapeHtml(b.inscription)}</div><div class="dialog-location"><strong>${escapeHtml(b.location)}</strong></div></div>`;dialog.showModal();}
searchInput.addEventListener('input',render);searchButton.addEventListener('click',render);searchInput.addEventListener('keydown',e=>{if(e.key==='Enter')render();});locationFilter.addEventListener('change',render);clearButton.addEventListener('click',()=>{searchInput.value='';locationFilter.value='';render();searchInput.focus();});dialogClose.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
fetch('bricks.json').then(r=>{if(!r.ok)throw new Error('Could not load brick data');return r.json();}).then(data=>{bricks=data;buildFrontGrid();render();}).catch(err=>{resultSummary.textContent=err.message;});